
server:
  port: 8088
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/ShopApp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_ROOT_PASSWORD:Abc123456789@}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
#      Flyway
#  đường dẫn script tới flyway
  flyway:
    locations: classpath:/db/migration,classpath:/dev/db/migration
#    Phiên bản baseline sẽ =1
    baseline-on-migrate: true
    baseline-version: 0
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  kafka:
    client:
      dns:
        lookup: use_dns_cache
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        "[spring.json.type.mapping]": category:com.project.shopapp.models.Category
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    bootstrap-servers: ${KAFKA_BROKER_SERVER:localhost}:${KAFKA_BROKER_PORT:9092}



#  messages:
#    basename: i18n/messages
#    encoding: UTF-8
#    default-locale: en
api:
  prefix: api/v1

jwt:
  expiration: 2592000
  expiration-refresh-token: 5184000
  secretKey: qDiiLDaBQrPUAf+0c++xV+EjS6puVcGx/QYhYHQ7gu0=
logging:
  level:
    org:
     springframework.security: DEBUG

#     HealthCheck
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        include: "health, info"
#Swagger
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#  api-docs:
#    path: /api-docs
#  show-actuator: true